# Generated by Django 5.1.2 on 2024-10-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(choices=[('pdf', 'pdf'), ('epub', 'epub'), ('mp3', 'mp3')], default='pdf', max_length=4)),
                ('size', models.PositiveIntegerField(default=0)),
                ('publish_date', models.DateField(null=True)),
                ('page_count', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='app_book.category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.publisher')),
            ],
        ),
    ]
